### ISSUE TITLE
Image is being rotated and not correctly resizes on MacOS/Macbook M1

### ISSUE THREAD

**Issue by jimtyrro** [SalOne22/rimage#104]
## Description:
**Describe the bug**

When executing `rimage -q 75 --width 1300 --height 600 -o ./output -s _updated sample-1.jpg` command with both `--width` and `--height` -- it rotates the image 90 deg clockwise and then applies 1300 x 600 size but the image width now becomes the height so it appears squeezed. (See sample-1.jpg below).

If I specify just `--width`:  `rimage -q 75 --width 1300 -o ./output -s _updated sample-2.jpg` -- it rotates the image 90 deg clockwise and then applies correctly 1300 width. (See sample-2.jpg below).

If I specify just `--height` -- then it rotes it 90 deg clockwise and is applies height to the with of the original image making image 276 x 600 px. (See sample-3.jpg)

## Steps To Reproduce:

1. Run command(s): 
1.1. `rimage -q 75 --width 1300 --height 600 -o ./output -s _updated sample-1.jpg`
1.2  `rimage -q 75 --width 1300 -o ./output -s _updated sample-2.jpg`
1.3 `rimage -q 75 --height 600 -o ./output -s _updated sample-3.jpg`

2. See resultant images.

## Expected behavior:

Should not rotate or squeeze image.

## Images

1. Sample-1.jpg
![sample-1](https://github.com/SalOne22/rimage/assets/12877886/44e455d5-3e09-4796-bc4d-21cdc61b7d91)

2. Sample-2.jpg
![sample-2](https://github.com/SalOne22/rimage/assets/12877886/ec035df6-83d3-4010-8865-fb364c8d1e82)

3. Sample-3..jpg
![sample-3](https://github.com/SalOne22/rimage/assets/12877886/937aa083-ea11-4ca5-bb1d-789df79af0cf)

## Additional info:
**Desktop (please complete the following information):**
 - OS: MacOS 12.6.8
 - Version: 0.8.2

**Comment by SalOne22** [comment]
After some research I found the source of the problem: your image has an EXIF ​​orientation header that is not being processed correctly. More information here - https://magnushoff.com/articles/jpeg-orientation/
Started working on this issue.

**Comment by jimtyrro** [comment]
I suspected that it might have something to do with EXIF data in my images. So it would be wonderful if you could implement auto-orientation capability. 

Thank you so much for being so responsive.

**Comment by jimtyrro** [comment]
Hi Vlad,

Any updates on this issue? Did you make any progress?

Thanks.

**Comment by SalOne22** [comment]
Yes, I have fixed this issue in new library, now I struggle with binary to work properly.  In new release this problem should be fixed

**Comment by SalOne22** [comment]
New release has been out, please check for this issue again
