### ISSUE TITLE
[Bug]: Path error when it contains "-","[","]",etc.

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the image file path contains special symbols such as "-", "[", etc., the program cannot recognize the path correctly.

![图片](https://github.com/SalOne22/rimage/assets/63829496/94138168-94d0-4b61-8143-c35edb77a465)

### Expected behavior

No error

### Library Version

0.9.0 (latest)

### Steps To Reproduce

None

### Anything else?

None

**Comment by SalOne22** [comment]
new release has been out, please check for this issue again

**Comment by Mikachu2333** [comment]
Thanks very much!

**Comment by SalOne22** [comment]
fixed in v0.9.0
