### ISSUE TITLE
[Bug]: Wander if "-t" opintion is avaliable.

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#123]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

The '-t'（thread）option has disappeared everywhere, and I would like to know if it is still avaliable

### Library Version

None

**Comment by Mikachu2333** [comment]
And, I try to find the release note to see if it has been removed in new version and I found nothing.

**Comment by Mikachu2333** [comment]
And, --quiet flag is also disappeared...

**Comment by SalOne22** [comment]
In 0.9.0 release threads was removed because of new library, and I just forgot to include it back, sorry about that. This feature is implemented in unreleased 0.9.1 release with hotfixes

**Comment by Mikachu2333** [comment]
Thanks for timely answer! Besides, would the version 0.9.1 be released soon? If so, I will slightly postpone the release plan of my GUI version. If the time exceeds a week, I will currently release a small update

**Comment by SalOne22** [comment]
New release should be done in under one week

**Comment by Mikachu2333** [comment]
Thanks!
