### ISSUE TITLE
[Feature]: Need tips about "could't find dll 'libstdc++-6.dll' "

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#126]
### Description

Many Chinese users email me about this and I've assisted them in handling it. (I have also encountered this problem) 

So, I wandered if you have compile the software with the "static" flag to avoid it. 
And, what is the cause of this problem?

**Comment by Mikachu2333** [comment]
This issues comes with the version 0.9.0, ver0.8.2 run successfully.

**Comment by SalOne22** [comment]
New version 0.9.0 introduces jpegxl format support, and can't be build on native windows msvc target, so we build it on gnu with mingw. Version 0.9.0 runs  only on windows gnu environment. With version 0.9.1 static builds will be enabled, to provide rimage to users without mingw.

**Comment by Mikachu2333** [comment]
Thanks for answer!
