### ISSUE TITLE
[Bug]: Ver0.9.1 has been released but couldn't find the executable file in Release page

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As mentioned in the question. But, github remind me that new releases have executable files...

![图片](https://github.com/SalOne22/rimage/assets/63829496/cc6b062e-fe46-4581-b79a-80b1ec42e1b1)
![图片](https://github.com/SalOne22/rimage/assets/63829496/91afda9d-dcb2-4874-87cd-d91161c1cdde)
![图片](https://github.com/SalOne22/rimage/assets/63829496/329a01bb-b7ad-43d9-8acb-eb23192ec840)
![图片](https://github.com/SalOne22/rimage/assets/63829496/c29ce059-afce-4a0a-9f3b-acf84dd973ad)

### Library Version

None

**Comment by Mikachu2333** [comment]
As an alternative, I found the "prepared for release" tag form Github Actions to test it.

**Comment by Mikachu2333** [comment]
Besides, file released from Git Action could not use "-t" option

**Comment by Mikachu2333** [comment]
And, I try to build rimage and no error encountered, but the program is only 2.47MB when use --release flag and 6.94MB when use "cargo build" only... What's wrong with it?

**Comment by SalOne22** [comment]
From version 0.9.0 binary executable is divided in several features, to enable all features use `--all-features` flag. Release 0.9.1 was accidentally released, sorry about that, I was testing windows builds.

**Comment by Mikachu2333** [comment]
ok
