### ISSUE TITLE
[Bug]: jxl output file is 0kb

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![图片](https://github.com/SalOne22/rimage/assets/63829496/26a7bc8b-6062-4463-8db3-b691d63ce8e5)
![图片](https://github.com/SalOne22/rimage/assets/63829496/478226a7-fa0e-45f5-8e6c-bc81ef7beebc)

Neither jpg nor png file input could output jxl file successfully.

### Library Version

None

**Comment by SalOne22** [comment]
segfault on gnu target 💀
On windows better to use msvc build without jpegxl, I will try to fix this in new releases, but this can take a lot of time.

**Comment by Mikachu2333** [comment]
To be honest, in my opinion, the jxl pic format is too unstable to use.... And, only a few people would like to try it...
Maybe deleting the support of JXL format until it becomes stable is a good idea...
And, maybe you'd better info users who want to try the latest version of this bug in your release note.

Besides, will you support heic format in the future?

**Comment by Mikachu2333** [comment]
I understand. And, do you have the plan to disable jxl feature on windows to reduce the size of the software?

By the way, I noticed that Rimage.exe you released on windows do not have any res info, would you decided to add it to the exe program?
(See: https://docs.rs/winres/0.1.12/winres/, or use rc.exe to add the res info to it)

**Comment by Mikachu2333** [comment]
Fixed successfully.
