### ISSUE TITLE
[Feature]: Preserve EXIF information for photos

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#135]
### Description

I found that the Exif information of the photo disappered after use. Can this be preserved?

(By user from appinn)

**Comment by Mikachu2333** [comment]
And, I found that sometimes when the input pic contains EXIF info, Rimage may rotate it automatically when output.

**Comment by SalOne22** [comment]
This behavior is intentional due to image minification and squoosh! compliance

**Comment by Mikachu2333** [comment]
Thanks for answer! I'll reply to him about this.
