### ISSUE TITLE
[Bug]: Pics' color will be changed if contains an ICC tag.

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![pic](https://meta-cdn1.appinn.com/uploads/default/original/3X/b/f/bffbe0b73ba184447477394c3df820280fb7941a.jpeg)

Here is a zipped file for this issue.
[Downloads.zip](https://github.com/SalOne22/rimage/files/13194621/Downloads.zip)

### Expected behavior

Compressed the Pic with right color.

### Library Version

0.9.1

**Comment by Mikachu2333** [comment]
Still need to fix atfer test.

**Comment by SalOne22** [comment]
ICC data issue will be fixed in the next major update.
