### ISSUE TITLE
[Feature]: Remove unused features.

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#152]
### Description

I use `cargo depgraph --all-deps | dot -Tpng > graph.png` to see the features and find that many of them are not used in the program.

Is it possible to remove them for program size reducing?

(_a.pdf_ and _b.pdf_ is the pic of which features rimage include)

[b.pdf](https://github.com/SalOne22/rimage/files/13712091/b.pdf)

[a.pdf](https://github.com/SalOne22/rimage/files/13712090/a.pdf)

### Problem or Motivation

Rimage's size is too large to use that I have to use the `UPX` and `strip.exe` to reduce the size of it for convience when I try to share it to my frineds.

And, I find that it is not impossible if the unused features of each dependence is included and complied to reduce the size...

So, maybe remove some unused features is a good idea to reduce the size, but I don't know how to solve it as a roob in Rust.

### Expected behavior

Size reducing.

**Comment by SalOne22** [comment]
Dependencies depicted with dashed lines in the dependency graph are linked to specific features. When preparing for a release, I use the `--all-features` flag, which activates all these dependencies. These are crucial for various functionalities like encoding, decoding etc. To further reduce the binary size, I consider using the optimization level `z`, which can make the executable approximately 15% smaller. While this optimization might impact performance, I haven't observed any significant slowdown on my system.

**Comment by SalOne22** [comment]
Released minor update, where reduce size slightly.

**Comment by Mikachu2333** [comment]
Thanks a lot!!!

**Comment by Mikachu2333** [comment]
I find that something interesting when I try to build release by myself with GNU target on my computer.

I compile the program with everything same and use `cargo build --all-features -r` and `strip -s rimage.exe` and found that my build's size is 14,782,478(14.7Mb) and your build is 14,832,640(14.8Mb) 🤣 

Though I use `lld.exe` to detect dlls my app use and your app use, no difference is found. The difference in size of program after compilation remains a mystery...🥲

-----

And I tried upx to re-reduce the size and had a great improvement (from 14.7Mb to 4.1Mb!). And, I plan to use the upx version on my GUI version.(The speed of the program was slightly reduced but not obviously)
`upx.exe -5 --lzma rimage.exe -o rimage_upx.exe`
