### ISSUE TITLE
[Bug]: Could not change size of pics

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As you can see, none of the following opinion could conv the pic size from 8960x3840 to 3480x1920.

Besides, I use the exe file compiled by myself and also failed with no error or warning, the pic output successfully but the size doesn't be changed.

![图片](https://github.com/SalOne22/rimage/assets/63829496/3cfe1c06-fcf9-40a5-9545-64709c42f832)
![图片](https://github.com/SalOne22/rimage/assets/63829496/1902e0a4-1891-4b82-a84e-8419bcd1fa6a)

### Expected behavior

Successfully change the size of pics.

### Library Version

0.10.1 (latest)

### Steps To Reproduce

Pic is [here](https://github.com/SalOne22/rimage/assets/63829496/e432c67d-95c4-4a05-bf2d-13ec4b5b8679)

Command: `rimage "D:\\Desktop\\test.jpg" -q 85 --codec jpg -r --suffix "_updated" --quantization 100 --dithering 100 --height 4480 --width 1920 -t 4`

**Comment by Mikachu2333** [comment]
Both v10 and v10.1 have the problem when resizing pic.

**Comment by SalOne22** [comment]
Fixed in #154
