### ISSUE TITLE
[Feature]: -r opinion improve

### ISSUE THREAD

**Issue by Mikachu2333** [SalOne22/rimage#171]
### Description

Is there any possible to add a fretrue that could _auto create a new subdirectory when output in original directory_ ?

Example:

Use `-r <new_folder>` opinion to make it, `-r` or `-r "" still maintaining original functionality

Before | After
-- | --
`D:\\test\\1.jpg` | `D:\\test\\jpg\\1_s.jpg`
`C:\\before\\5.png` | `C:\\before\\webp\\5_s.webp`

If you think this feature is too niche and not necessary, I can also implement it in my GUI

**Comment by SalOne22** [comment]
You can achieve similar result just using the `-o` option, I think that is unnecessary for cli.

**Comment by Mikachu2333** [comment]
ok, thanks for answer.
