### ISSUE TITLE
resize cannot Maintain aspect ratio

### ISSUE THREAD

**Issue by zhaoyun0071** [SalOne22/rimage#224]
### Description

Resize cannot Maintain aspect ratio

Previous versions can set --width or --height

but now cannot

**Comment by SalOne22** [comment]
In version 0.11.0, we changed `--width` and `--height` to a single option. Use `--size 500x_` to set width, height will be calculated automatically preserving aspect ratio. Use `--size _x500` to set only height.

Interface are subject to change, in new pre-release I will change it to `--size 500w` for width and `--size 500h` for height or return `--width` and `--height` back
