### ISSUE TITLE
[Bug]: Failed to convert tif to jpeg 

### ISSUE THREAD

**Issue by Kosette** [SalOne22/rimage#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Try to convert .tif to .jpeg, using  `rimage jpeg .\hello.tif`. Encounteed the following error:
`ERROR rimage > "hello.tif": IO error, Os { code: 3, kind: NotFound, message: "The system cannot the specific path." }`

### Expected behavior

convert tif to jpeg

### Library Version

0.11.0 (latest)

### Steps To Reproduce

`rimage mozjpeg/jpeg hello.tif`, convert any .tif file on Windows.

### Anything else?

OS: Win11
Rimage: 0.11.0-next.1

**Comment by SalOne22** [comment]
Hello, when we moved to `zune-image` tiff support was temporally removed. #232 returns it back, so tiff support will be added in nearest release

**Comment by SalOne22** [comment]
This issue should be fixed in the new release [v0.11.0-next.2](https://github.com/SalOne22/rimage/releases/tag/v0.11.0-next.2)
