### ISSUE TITLE
[Bug]: Unable to produce png format pic when outputing 无法输出png格式的图片

### ISSUE THREAD

**Issue by ferretgeek** [SalOne22/rimage#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

无论任何格式图片，均无法输出PNG，且也无执行过程

### Library Version

None

**Comment by Mikachu2333** [comment]
这里不是Rimage_GUI，请使用英文并详细描述！需要中文请去Rimage_GUI！！！

请仔细描述你做了什么，用了什么命令，系统环境。什么信息都不给对排查错误没有任何帮助。就好像你去医院看病，医生问你哪里不舒服，头疼肚子疼还是乏力，你说自己身体不舒服，医生能怎么帮助你？？？再见不送。

本issue将被关闭且不会被回答。

This is not Rimage_GUI and **doesn't support Chinese**. Please **use English** and carefully **describe why your error occurred**, the **command you used to run**, and the **system environment**.
