### ISSUE TITLE
[Bug]: How to build latest next

### ISSUE THREAD

**Issue by pepa65** [SalOne22/rimage#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to build `rimage@0.11.0-next.3` like this: `cargo install rimage@0.11.0-next.3 --features="build-binary"` (which might not be the right way..?), and get this:
```
error[E0432]: unresolved import `rimage::operations::icc`
  --> /home/pp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rimage-0.11.0-next.3/src/main.rs:20:25
   |
20 | use rimage::operations::icc::ApplySRGB;
   |                         ^^^ could not find `icc` in `operations`
   |
note: found an item that was configured out
  --> /home/pp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rimage-0.11.0-next.3/src/operations/mod.rs:12:9
   |
12 | pub mod icc;
   |         ^^^
note: the item is gated behind the `icc` feature
  --> /home/pp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rimage-0.11.0-next.3/src/operations/mod.rs:11:7
   |
11 | #[cfg(feature = "icc")]
   |       ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rimage` (bin "rimage") due to 1 previous error
error: failed to compile `rimage v0.11.0-next.3`, intermediate artifacts can be found at `/tmp/cargo-installA96116`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

### Expected behavior

I'm hoping to get an `rimage` v0.11.0-next.3

### Library Version

0.11.0 (latest)

### Steps To Reproduce

Linux Mint 22 (based on Ubuntu 24.04 LTS)
rustc 1.81.0 (eeb90cda1 2024-09-04)
Installed nasm (and yasm).

**Comment by SalOne22** [comment]
Hello, as a quick fix you can add `icc` to enabled features. I recommend for cli build to enable all features because features are designed mainly for library users

**Comment by pepa65** [comment]
Great! This builds: `cargo install rimage@0.11.0-next.3 --features="build-binary" --features="icc"`.

Are there any other features I am missing out on??

**Comment by SalOne22** [comment]
All other features are enabled by default

**Comment by pepa65** [comment]
Excellent! Thanks for making this.
