### ISSUE TITLE
Custom Output Directory

### ISSUE THREAD

**Issue by echocrow** [SalOne22/rimage#50]
An output path option (e.g. `-o, --output <PATH>`) where resulting images will be written to.

## Description
At the moment, rimage only seems to write output images next to their source assets (i.e. into the same folder). Instead, I often found it convenient to output images into a separate directory, allowing me to easily separate raw input and minified output assets.

## Required libraries:
(No Rust expert, but I'm guessing none?)

## Expected Behavior:
Running, for example, `rimgae -q 75 -o ./out ./in/*.png` would write the compressed JPGs into the `./out/` directory, instead of writing any inside `./in/`.

One notable edge case: Nested folders. E.g. running `rimgae -q 75 -o ./out ./in/*/*.png`, let's assume `./in/foo/bar.png` exists. Here, this asset would be outputted as `./out/foo/bar.jpg`. It would be great if the `./out/foo` directory was created automatically if it didn't exist yet.

## Note:
Current workaround requires use of `--suffix` (or for outputted files to use a different format/extension than their source counterparts), and then some find/mv shenanigans based on file names or mtime to separate source and output files.

**Additional context**
It was recently announced that [`@squoosh/cli`](https://www.npmjs.com/package/@squoosh/cli) is no longer being maintained. Looking for alternatives led me to this little gem. 💎

**Comment by SalOne22** [comment]
That's a good issue! I completely forgot about the output directory, so now I will try to implement this. Thanks for the suggestion!

**Comment by echocrow** [comment]
thanks for the fast turnaround! 🚀 glad to have `rimage`, now that `@squoosh/cli` was sunset 🪦
