### ISSUE TITLE
CLI progress bar spamming

### ISSUE THREAD

**Issue by Explorare** [SalOne22/rimage#90]
## Environment
Windows 10 22H2
Powershell v7.3.6
oh-my-posh v18.2.0
Windows Terminal v1.18.1462.0
rimage v0.8.1

## Description:
As shown in release message v0.8.1, the progress bar should update in the same place, but in my environment it creates a new line every time the content update.
Is this an upstream issue?

## Expected behavior:
![v0.8.1](https://github.com/SalOne22/rimage/raw/v0.8.1/assets/progress_bar.gif)

## Images
![image](https://github.com/SalOne22/rimage/assets/5090766/603071ad-3d7f-4835-9bc1-d23b03138faf)

**Comment by SalOne22** [comment]
Hello, I removed this progress bar for a while, but from version [v0.11.0-next.2](https://github.com/SalOne22/rimage/releases/tag/v0.11.0-next.2) new progress bar is added. Can you check that this issue is resolved?

**Comment by Explorare** [comment]
Thank you for fix. It now works like a charm. 🚀
[ENV]
Windows 10 22H2
Powershell v7.4.2
oh-my-posh v21.25.0
Windows Terminal v1.21.1772.0
rimage [v0.11.0-next.2](https://github.com/SalOne22/rimage/releases/tag/v0.11.0-next.2)
