### ISSUE TITLE
can't correctly process filenames with square brackets

### ISSUE THREAD

**Issue by Kosette** [SalOne22/rimage#91]
## Description:
Any files with square brackets in filename will be ignored. Both `rimage.exe *.jpg` and `rimage.exe aaa[bbb].jpg` result the same.

## Additional info:
 - OS: Win11
 - Shell: Powershell
 - Version 0.8.1

**Comment by SalOne22** [comment]
This will be fixed in new release, if it cant expand glob pattern, will use input as default.
