### ISSUE TITLE
Cannot handle extension capitalized photos, such as the extension of JPG

### ISSUE THREAD

**Issue by wyl0205** [SalOne22/rimage#93]
## Description:
Cannot process photos with uppercase extensions, such as JPG format. Lowercase jpg without any issues.

## Steps To Reproduce:
D:\rimage-0.8.1-x86_64-pc-windows-msvc>rimage -q 75 IMG_0061.JPG  -o IMG_0061_new.jpg
Failed   IMG_0061.JPG failed: JPG is not supported
D:\rimage-0.8.1-x86_64-pc-windows-msvc>rimage -q 75 IMG_0065.jpg  -o IMG_0065_new.jpg
Done   IMG_0065.jpg completed 4.09 MB -> 1.58 MB v 61.4%

## Additional info:
**Desktop (please complete the following information):cmd (Microsoft Windows [版本 10.0.17763.316])
 - OS: [Win10 Ltsc2019]
 - Version [0.8.1]

**Comment by Mikachu2333** [comment]
This bug seems to have been fixed before

https://github.com/SalOne22/rimage/issues/67#issuecomment-1609132410

**Comment by wyl0205** [comment]
But the latest version 0.8.1 seems to have introduced

**Comment by wyl0205** [comment]
Version 0.7.1 does not have this issue

**Comment by Mikachu2333** [comment]
> Version 0.7.1 does not have this issue

![图片](https://github.com/SalOne22/rimage/assets/63829496/b4d59d09-d8e2-4710-b93c-19e02f663db8)
